# Generated by Django 5.2.1 on 2025-05-30 16:16

import django.db.models.deletion
import sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('tenantId', models.CharField(default='', max_length=500)),
                ('url', models.CharField(default='', max_length=500)),
                ('urlType', models.CharField(default='', max_length=500)),
                ('published', models.BooleanField(default=False)),
                ('logo', models.CharField(default='', max_length=500)),
                ('favicon', models.CharField(default='', max_length=500)),
                ('primaryColor', models.CharField(default='', max_length=50)),
                ('secondaryColor', models.CharField(default='', max_length=50)),
                ('welcomeMessage', models.TextField(default='')),
                ('language', models.CharField(default='', max_length=50)),
                ('lastPublished', models.DateField()),
                ('visitorTypes', models.JSONField(default=list)),
                ('formFields', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=500)),
                ('expectedDuration', models.CharField(default='', max_length=50)),
                ('host', models.CharField(default='', max_length=500)),
                ('name', models.CharField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=500)),
                ('purpose', models.CharField(default='', max_length=500)),
                ('signature', models.CharField(default='', max_length=500)),
                ('visitorType', models.CharField(default='', max_length=500)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='visitorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=sites.models.upload_visitor_file)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitorPhoto', to='sites.visitor')),
            ],
        ),
    ]
