# Generated by Django 5.2.1 on 2025-05-30 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=500)),
                ('department', models.CharField(default='', max_length=500)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='sites.site')),
            ],
        ),
        migrations.AlterField(
            model_name='visitor',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='sites.host'),
        ),
    ]
