# Generated by Django 5.2.1 on 2025-05-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_host_alter_visitor_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='timezoneOffset',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='lastPublished',
            field=models.DateField(blank=True, null=True),
        ),
    ]
