# Generated by Django 5.2.1 on 2025-05-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_site_timezoneoffset_alter_site_lastpublished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='favicon',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='primaryColor',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='secondaryColor',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='urlType',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='welcomeMessage',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
