# Generated by Django 5.2.1 on 2025-05-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_site_favicon_alter_site_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='lastPublished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
